/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts with their current balance */
        get: operations["list-accounts"];
        put?: never;
        /** Create an account */
        post: operations["create-account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create several accounts
         * @description Creates up to 100 accounts in a single transaction: if any item is invalid, nothing is created. Errors point at the failing item, e.g. items[3].name.
         */
        post: operations["create-accounts-batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an account */
        get: operations["get-account"];
        put?: never;
        post?: never;
        /**
         * Delete an account
         * @description Permanently deletes an account without transactions. Accounts with transactions must be archived instead.
         */
        delete: operations["delete-account"];
        options?: never;
        head?: never;
        /**
         * Update an account
         * @description Partially updates an account. The currency cannot be changed. Set archived to true to hide the account.
         */
        patch: operations["update-account"];
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a sign-in email
         * @description Sends a magic link and a six-digit code to the address if it belongs to an allowed user. The response is the same whether or not the address is known.
         */
        post: operations["request-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in user */
        get: operations["get-current-user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the signed-in user's profile */
        patch: operations["update-current-user"];
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a magic link token or code for a session
         * @description Provide either `token`, or `email` and `code`. Returns a bearer token for subsequent requests.
         */
        post: operations["verify-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: operations["list-categories"];
        put?: never;
        /** Create a category */
        post: operations["create-category"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create several categories
         * @description Creates up to 100 categories in a single transaction: if any item is invalid, nothing is created. Errors point at the failing item, e.g. items[3].name.
         */
        post: operations["create-categories-batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a category */
        get: operations["get-category"];
        put?: never;
        post?: never;
        /**
         * Delete a category
         * @description Deletes a category. Its transactions are kept and become uncategorized.
         */
        delete: operations["delete-category"];
        options?: never;
        head?: never;
        /**
         * Update a category
         * @description Partially updates a category. The kind cannot be changed.
         */
        patch: operations["update-category"];
        trace?: never;
    };
    "/api/v1/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported currencies */
        get: operations["list-currencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recurring items
         * @description Subscriptions, bills, installments and recurring income, with their next due date.
         */
        get: operations["list-recurring-items"];
        put?: never;
        /** Create a recurring item */
        post: operations["create-recurring-item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Committed monthly cost
         * @description Active recurring items normalized to an average month and grouped per currency (no conversion), split into expenses and income.
         */
        get: operations["get-recurring-summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upcoming recurring payments
         * @description Due dates of active items in the next days (today included) with their status, plus the current period of items that are overdue. Ordered by due date.
         */
        get: operations["list-upcoming-recurring"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a recurring item */
        get: operations["get-recurring-item"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a recurring item
         * @description Partially updates an item. The type and account cannot be changed. There is no delete: set status to cancelled to retire an item.
         */
        patch: operations["update-recurring-item"];
        trace?: never;
    };
    "/api/v1/recurring/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a payment
         * @description Creates the transaction for one period of an active item (type, account, category and description come from the item) and links it. The item's estimate is not changed by the amount paid.
         */
        post: operations["register-recurring-payment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Income and expense summary
         * @description Totals per currency for a period, broken down by category, plus current balances. Transfers are excluded from income and expenses.
         */
        get: operations["get-summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transactions
         * @description Returns transactions, newest first, with optional filters.
         */
        get: operations["list-transactions"];
        put?: never;
        /**
         * Create a transaction
         * @description Records an expense, an income, or a transfer between two accounts.
         */
        post: operations["create-transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create several transactions
         * @description Creates up to 100 transactions in a single transaction: if any item is invalid, nothing is created. Errors point at the failing item, e.g. items[3].name.
         */
        post: operations["create-transactions-batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a transaction */
        get: operations["get-transaction"];
        /**
         * Replace a transaction
         * @description Replaces every field of a transaction.
         */
        put: operations["replace-transaction"];
        post?: never;
        /** Delete a transaction */
        delete: operations["delete-transaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Link a transaction to a recurring item
         * @description The transaction must have the item's type and account. An already linked transaction is re-linked. Several transactions may settle the same period.
         */
        put: operations["link-transaction-recurring"];
        post?: never;
        /**
         * Unlink a transaction from its recurring item
         * @description Does nothing when the transaction is not linked.
         */
        delete: operations["unlink-transaction-recurring"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Reports whether the API and its database are reachable.
         */
        get: operations["get-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Account.json
             */
            readonly $schema?: string;
            archived: boolean;
            /**
             * Format: int64
             * @description Current balance in minor units
             */
            balance: number;
            /** Format: date-time */
            created_at: string;
            /** @example MXN */
            currency: string;
            id: string;
            /**
             * Format: int64
             * @description Opening balance in minor units
             */
            initial_balance: number;
            /**
             * Format: int64
             * @example 2
             */
            minor_units: number;
            /** @example BBVA Checking */
            name: string;
            /** @enum {string} */
            type: "checking" | "savings" | "credit_card" | "cash" | "investment" | "other";
            /** Format: date-time */
            updated_at: string;
        };
        BatchInputCreateAccountInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BatchInputCreateAccountInputBody.json
             */
            readonly $schema?: string;
            /** @description Items to create (1 to 100). All are created or none are */
            items: components["schemas"]["CreateAccountInput"][];
        };
        BatchInputCreateCategoryInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BatchInputCreateCategoryInputBody.json
             */
            readonly $schema?: string;
            /** @description Items to create (1 to 100). All are created or none are */
            items: components["schemas"]["CreateCategoryInput"][];
        };
        BatchInputTransactionInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BatchInputTransactionInputBody.json
             */
            readonly $schema?: string;
            /** @description Items to create (1 to 100). All are created or none are */
            items: components["schemas"]["TransactionInput"][];
        };
        Category: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Category.json
             */
            readonly $schema?: string;
            archived: boolean;
            /** @example #22c55e */
            color: string | null;
            /** Format: date-time */
            created_at: string;
            /** @example shopping-cart */
            icon: string | null;
            id: string;
            /** @enum {string} */
            kind: "expense" | "income";
            /** @example Groceries */
            name: string;
            /** Format: date-time */
            updated_at: string;
        };
        CategoryTotal: {
            category_color: string | null;
            /** @description Null for uncategorized transactions */
            category_id: string | null;
            category_name: string | null;
            /**
             * Format: int64
             * @description Total in minor units
             */
            total: number;
            /** Format: int64 */
            transaction_count: number;
        };
        CreateAccountInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateAccountInput.json
             */
            readonly $schema?: string;
            /**
             * @description ISO 4217 currency code
             * @example MXN
             */
            currency: string;
            /**
             * Format: int64
             * @description Opening balance in minor units (may be negative, e.g. credit cards)
             */
            initial_balance?: number;
            name: string;
            /** @enum {string} */
            type: "checking" | "savings" | "credit_card" | "cash" | "investment" | "other";
        };
        CreateCategoryInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateCategoryInput.json
             */
            readonly $schema?: string;
            color?: string;
            icon?: string;
            /** @enum {string} */
            kind: "expense" | "income";
            name: string;
        };
        CreateRecurringItemInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateRecurringItemInput.json
             */
            readonly $schema?: string;
            /**
             * Format: uuid
             * @description Account that is charged or credited; its currency applies to the item
             */
            account_id: string;
            /**
             * Format: int64
             * @description Estimated amount of each occurrence, in minor units
             */
            amount: number;
            /**
             * Format: uuid
             * @description Category whose kind matches the type
             */
            category_id?: string;
            /**
             * Format: int64
             * @description Repeats every this many units
             * @default 1
             */
            interval_count: number;
            /** @enum {string} */
            interval_unit: "week" | "month" | "year";
            name: string;
            notes?: string;
            /**
             * Format: date
             * @description First due date. Defaults to today
             */
            start_on?: string;
            /**
             * Format: int64
             * @description Number of payments for an installment plan. Omit for open-ended items
             */
            total_payments?: number;
            /** @enum {string} */
            type: "expense" | "income";
        };
        Currency: {
            /** @example MXN */
            code: string;
            /**
             * Format: int64
             * @description Number of decimal places; amounts are expressed in these minor units
             * @example 2
             */
            minor_units: number;
            /** @example Mexican Peso */
            name: string;
            /** @example $ */
            symbol: string;
        };
        CurrencySummary: {
            /**
             * Format: int64
             * @description Current combined balance of active accounts in this currency
             */
            balance: number;
            /** @example MXN */
            currency: string;
            /**
             * Format: int64
             * @description Total expenses in the period, in minor units
             */
            expense: number;
            /** @description Expenses by category, largest first */
            expenses: components["schemas"]["CategoryTotal"][];
            /**
             * Format: int64
             * @description Total income in the period, in minor units
             */
            income: number;
            /** @description Income by category, largest first */
            incomes: components["schemas"]["CategoryTotal"][];
            /**
             * Format: int64
             * @example 2
             */
            minor_units: number;
            /**
             * Format: int64
             * @description Income minus expenses
             */
            net: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][];
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Database connectivity status
             * @example ok
             */
            database: string;
            /**
             * @description Overall service status
             * @example ok
             */
            status: string;
        };
        LinkRecurringInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LinkRecurringInput.json
             */
            readonly $schema?: string;
            /**
             * Format: date
             * @description Due date being paid; must be a due date of the item. Defaults to the due date closest to the transaction date
             */
            period?: string;
            /** Format: uuid */
            recurring_id: string;
        };
        ListOutputAccountBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListOutputAccountBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["Account"][];
        };
        ListOutputCategoryBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListOutputCategoryBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["Category"][];
        };
        ListOutputCurrencyBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListOutputCurrencyBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["Currency"][];
        };
        ListOutputRecurringItemBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListOutputRecurringItemBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["RecurringItem"][];
        };
        ListOutputTransactionBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListOutputTransactionBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["Transaction"][];
        };
        ListOutputUpcomingRecurringBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListOutputUpcomingRecurringBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["UpcomingRecurring"][];
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LoginInputBody.json
             */
            readonly $schema?: string;
            /** Format: email */
            email: string;
            /**
             * @description Language of the email; defaults to the user's preference
             * @enum {string}
             */
            locale?: "en" | "es";
        };
        LoginOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LoginOutputBody.json
             */
            readonly $schema?: string;
            message: string;
        };
        RecurringCurrencySummary: {
            /** @example MXN */
            currency: string;
            /**
             * Format: int64
             * @description Committed monthly expenses, in minor units
             */
            expense: number;
            /**
             * Format: int64
             * @description Active recurring expenses included
             */
            expense_count: number;
            /**
             * Format: int64
             * @description Expected monthly recurring income, in minor units
             */
            income: number;
            /**
             * Format: int64
             * @description Active recurring incomes included
             */
            income_count: number;
            /**
             * Format: int64
             * @example 2
             */
            minor_units: number;
            /**
             * Format: int64
             * @description Income minus expenses
             */
            net: number;
        };
        RecurringItem: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RecurringItem.json
             */
            readonly $schema?: string;
            account_id: string;
            account_name: string;
            /**
             * Format: int64
             * @description Estimated amount of each occurrence, in minor units
             */
            amount: number;
            category_id: string | null;
            category_name: string | null;
            /** Format: date-time */
            created_at: string;
            /** @example MXN */
            currency: string;
            /** @description Period the item is in now (latest due date on or before today). Null unless the item is active */
            current_period: components["schemas"]["RecurringPeriod"];
            id: string;
            /**
             * Format: int64
             * @description Repeats every this many units
             */
            interval_count: number;
            /** @enum {string} */
            interval_unit: "week" | "month" | "year";
            /**
             * Format: date
             * @description Final due date of an installment plan; null when open-ended
             */
            last_due_on: string | null;
            /** @description Most recent linked transaction */
            last_payment: components["schemas"]["RecurringPayment"];
            /**
             * Format: int64
             * @example 2
             */
            minor_units: number;
            /**
             * Format: int64
             * @description Amount normalized to an average month, in minor units (rounded half up)
             */
            monthly_amount: number;
            /** @example Netflix */
            name: string;
            /**
             * Format: date
             * @description Next due date on or after today. Null unless the item is active and still has due dates
             */
            next_due_on: string | null;
            notes: string;
            /**
             * Format: date
             * @description First due date
             */
            start_on: string;
            /** @enum {string} */
            status: "active" | "paused" | "cancelled";
            /**
             * Format: int64
             * @description Number of payments for installment plans; null when open-ended
             */
            total_payments: number | null;
            /** @enum {string} */
            type: "expense" | "income";
            /** Format: date-time */
            updated_at: string;
        };
        RecurringPayment: {
            /**
             * Format: int64
             * @description Amount actually paid, in minor units
             */
            amount: number;
            /**
             * Format: date
             * @description Date of the transaction
             */
            date: string;
            /**
             * Format: date
             * @description Due date (period) the payment settles
             */
            due_on: string;
            transaction_id: string;
        };
        RecurringPaymentInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RecurringPaymentInput.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Amount actually paid, in minor units. Defaults to the item's estimate, which is never changed by a payment
             */
            amount?: number;
            /**
             * Format: date
             * @description Date of the transaction. Defaults to today
             */
            date?: string;
            /**
             * Format: date
             * @description Due date being paid; must be a due date of the item. Defaults to the due date closest to date
             */
            period?: string;
        };
        RecurringPeriod: {
            /** Format: date */
            due_on: string;
            /**
             * @description paid: a linked transaction exists for this due date. overdue: the due date is before today and it is not paid. pending: otherwise
             * @enum {string}
             */
            status: "paid" | "pending" | "overdue";
        };
        RecurringSummary: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RecurringSummary.json
             */
            readonly $schema?: string;
            currencies: components["schemas"]["RecurringCurrencySummary"][];
        };
        Session: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Session.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            expires_at: string;
            /** @description Bearer token; only returned when the session is created */
            token?: string;
            user: components["schemas"]["User"];
        };
        Summary: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Summary.json
             */
            readonly $schema?: string;
            currencies: components["schemas"]["CurrencySummary"][];
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        Transaction: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Transaction.json
             */
            readonly $schema?: string;
            /** Format: uuid */
            account_id: string;
            account_name: string;
            /**
             * Format: int64
             * @description Positive amount in minor units of the account currency
             */
            amount: number;
            /** Format: uuid */
            category_id: string | null;
            category_name: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Omitted when the creator is unknown */
            created_by?: components["schemas"]["UserRef"];
            /** @example MXN */
            currency: string;
            description: string;
            /** Format: uuid */
            destination_account_id: string | null;
            destination_account_name: string | null;
            /**
             * Format: int64
             * @description Amount received by the destination account (transfers only)
             */
            destination_amount: number | null;
            destination_currency: string | null;
            /** Format: int64 */
            destination_minor_units: number | null;
            id: string;
            /**
             * Format: int64
             * @example 2
             */
            minor_units: number;
            /**
             * Format: date
             * @example 2026-10-04
             */
            occurred_on: string;
            /**
             * Format: date
             * @description Due date (period) of the recurring item this transaction settles
             */
            recurring_due_on: string | null;
            /**
             * Format: uuid
             * @description Recurring item this transaction pays, if any
             */
            recurring_id: string | null;
            /** @enum {string} */
            type: "expense" | "income" | "transfer";
            /** Format: date-time */
            updated_at: string;
        };
        TransactionInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TransactionInput.json
             */
            readonly $schema?: string;
            /**
             * Format: uuid
             * @description Source account (the account charged for expenses and transfers, credited for income)
             */
            account_id: string;
            /**
             * Format: int64
             * @description Positive amount in minor units of the account currency
             */
            amount: number;
            /**
             * Format: uuid
             * @description Category whose kind matches the type (not allowed for transfers)
             */
            category_id?: string;
            description?: string;
            /**
             * Format: uuid
             * @description Required for transfers
             */
            destination_account_id?: string;
            /**
             * Format: int64
             * @description Amount received by the destination account. Required for transfers between currencies; defaults to amount otherwise
             */
            destination_amount?: number;
            /**
             * Format: date
             * @description Defaults to today
             */
            occurred_on?: string;
            /** @enum {string} */
            type: "expense" | "income" | "transfer";
        };
        TransactionPage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TransactionPage.json
             */
            readonly $schema?: string;
            items: components["schemas"]["Transaction"][];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        UpcomingRecurring: {
            /** Format: date */
            due_on: string;
            item: components["schemas"]["RecurringItem"];
            /** @enum {string} */
            status: "paid" | "pending" | "overdue";
        };
        UpdateAccountInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateAccountInput.json
             */
            readonly $schema?: string;
            archived?: boolean;
            /** Format: int64 */
            initial_balance?: number;
            name?: string;
            /** @enum {string} */
            type?: "checking" | "savings" | "credit_card" | "cash" | "investment" | "other";
        };
        UpdateCategoryInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateCategoryInput.json
             */
            readonly $schema?: string;
            archived?: boolean;
            /** @description Hex color (#rrggbb); empty string clears it */
            color?: string;
            /** @description Icon name; empty string clears it */
            icon?: string;
            name?: string;
        };
        UpdateProfileInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateProfileInput.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            locale?: "en" | "es";
            name?: string;
        };
        UpdateRecurringItemInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateRecurringItemInput.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            amount?: number;
            /** Format: uuid */
            category_id?: string;
            /** @description Remove the category */
            clear_category?: boolean;
            clear_total_payments?: boolean;
            /** Format: int64 */
            interval_count?: number;
            /** @enum {string} */
            interval_unit?: "week" | "month" | "year";
            name?: string;
            notes?: string;
            /** Format: date */
            start_on?: string;
            /**
             * @description Set to cancelled to retire the item
             * @enum {string}
             */
            status?: "active" | "paused" | "cancelled";
            /** Format: int64 */
            total_payments?: number;
        };
        User: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/User.json
             */
            readonly $schema?: string;
            /** Format: email */
            email: string;
            id: string;
            /** @enum {string} */
            locale: "en" | "es";
            name: string;
        };
        UserRef: {
            email: string;
            id: string;
            name: string;
        };
        VerifyInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/VerifyInputBody.json
             */
            readonly $schema?: string;
            /** @description Six-digit code from the email */
            code?: string;
            /** @description Email address, required together with code */
            email?: string;
            /** @description Token from the magic link */
            token?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-accounts": {
        parameters: {
            query?: {
                /** @description Include archived accounts */
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOutputAccountBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-accounts-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchInputCreateAccountInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOutputAccountBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-account": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-account": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-account": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "request-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-current-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-current-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "verify-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-categories": {
        parameters: {
            query?: {
                /** @description Filter by kind */
                kind?: "expense" | "income";
                /** @description Include archived categories */
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOutputCategoryBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-categories-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchInputCreateCategoryInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOutputCategoryBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-category": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-category": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-category": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOutputCurrencyBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-recurring-items": {
        parameters: {
            query?: {
                /** @description Only items with this status */
                status?: "active" | "paused" | "cancelled";
                /** @description Only items of this type */
                type?: "expense" | "income";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOutputRecurringItemBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-recurring-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringItemInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringItem"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-recurring-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-upcoming-recurring": {
        parameters: {
            query?: {
                /** @description Look this many days ahead (today included) */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOutputUpcomingRecurringBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-recurring-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringItem"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-recurring-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringItemInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringItem"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "register-recurring-payment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringPaymentInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-summary": {
        parameters: {
            query?: {
                /** @description Inclusive start date; defaults to the first day of the current month */
                from?: string;
                /** @description Inclusive end date; defaults to the last day of the current month */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-transactions": {
        parameters: {
            query?: {
                /** @description Transactions where the account is the source or the destination */
                account_id?: string;
                category_id?: string;
                type?: "expense" | "income" | "transfer";
                /** @description Inclusive start date */
                from?: string;
                /** @description Inclusive end date */
                to?: string;
                /** @description Search in the description */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-transaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-transactions-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchInputTransactionInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOutputTransactionBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-transaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "replace-transaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-transaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "link-transaction-recurring": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRecurringInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "unlink-transaction-recurring": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
