// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAccountTransactions = `-- name: CountAccountTransactions :one
SELECT count(*) FROM transactions WHERE account_id = $1 OR destination_account_id = $1
`

func (q *Queries) CountAccountTransactions(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountTransactions, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, type, currency, initial_balance, balance_as_of)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateAccountParams struct {
	Name           string
	Type           string
	Currency       string
	InitialBalance int64
	BalanceAsOf    time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.InitialBalance,
		arg.BalanceAsOf,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT
    a.id, a.workspace_id, a.name, a.type, a.currency, a.initial_balance, a.archived_at, a.created_at, a.updated_at, a.balance_as_of,
    c.minor_units,
    (a.initial_balance + COALESCE(b.delta, 0))::bigint AS balance
FROM accounts a
JOIN currencies c ON c.code = a.currency
LEFT JOIN LATERAL (
    SELECT sum(
        CASE
            WHEN t.account_id = a.id AND t.type = 'income' THEN t.amount
            WHEN t.account_id = a.id THEN -t.amount
            ELSE t.destination_amount
        END
    ) AS delta
    FROM transactions t
    WHERE (t.account_id = a.id OR t.destination_account_id = a.id)
      AND t.occurred_on > a.balance_as_of
) b ON true
WHERE a.id = $1
`

type GetAccountRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	Name           string
	Type           string
	Currency       string
	InitialBalance int64
	ArchivedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	BalanceAsOf    time.Time
	MinorUnits     int16
	Balance        int64
}

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InitialBalance,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BalanceAsOf,
		&i.MinorUnits,
		&i.Balance,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many

SELECT
    a.id, a.workspace_id, a.name, a.type, a.currency, a.initial_balance, a.archived_at, a.created_at, a.updated_at, a.balance_as_of,
    c.minor_units,
    (a.initial_balance + COALESCE(b.delta, 0))::bigint AS balance
FROM accounts a
JOIN currencies c ON c.code = a.currency
LEFT JOIN LATERAL (
    SELECT sum(
        CASE
            WHEN t.account_id = a.id AND t.type = 'income' THEN t.amount
            WHEN t.account_id = a.id THEN -t.amount
            ELSE t.destination_amount
        END
    ) AS delta
    FROM transactions t
    WHERE (t.account_id = a.id OR t.destination_account_id = a.id)
      AND t.occurred_on > a.balance_as_of
) b ON true
WHERE $1::boolean OR a.archived_at IS NULL
ORDER BY a.archived_at IS NOT NULL, lower(a.name)
`

type ListAccountsRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	Name           string
	Type           string
	Currency       string
	InitialBalance int64
	ArchivedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	BalanceAsOf    time.Time
	MinorUnits     int16
	Balance        int64
}

// Balance = initial balance + income - expenses - transfers out + transfers in,
// counting only transactions dated after the account's balance_as_of day
// (the initial balance already includes everything up to and including it).
// Transfers apply the rule per side, using each account's own anchor.
func (q *Queries) ListAccounts(ctx context.Context, includeArchived bool) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.InitialBalance,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BalanceAsOf,
			&i.MinorUnits,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET
    name = COALESCE($1, name),
    type = COALESCE($2, type),
    initial_balance = COALESCE($3, initial_balance),
    balance_as_of = COALESCE($4, balance_as_of),
    archived_at = CASE
        WHEN $5::boolean IS NULL THEN archived_at
        WHEN $5::boolean THEN COALESCE(archived_at, now())
        ELSE NULL
    END
WHERE id = $6
`

type UpdateAccountParams struct {
	Name           *string
	Type           *string
	InitialBalance *int64
	BalanceAsOf    *time.Time
	Archived       *bool
	ID             uuid.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.InitialBalance,
		arg.BalanceAsOf,
		arg.Archived,
		arg.ID,
	)
	return err
}
