// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_deletion.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelUserDeletion = `-- name: CancelUserDeletion :execrows
UPDATE users SET deletion_scheduled_for = NULL
WHERE id = $1 AND deletion_scheduled_for IS NOT NULL
`

func (q *Queries) CancelUserDeletion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelUserDeletion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueUserDeletion = `-- name: ClaimDueUserDeletion :one
SELECT id, email, name, locale, created_at, updated_at, deletion_scheduled_for FROM users
WHERE deletion_scheduled_for <= $1
ORDER BY deletion_scheduled_for
LIMIT 1
FOR UPDATE SKIP LOCKED
`

// Picks one user whose grace period is over and locks them, skipping users
// another API instance is already deleting.
func (q *Queries) ClaimDueUserDeletion(ctx context.Context, deletionScheduledFor *time.Time) (User, error) {
	row := q.db.QueryRow(ctx, claimDueUserDeletion, deletionScheduledFor)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionScheduledFor,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

// Deletes the user with their sessions, login challenges and OAuth grants,
// codes and tokens (ON DELETE CASCADE). Rows they created in workspaces
// they leave are kept without attribution (ON DELETE SET NULL).
func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserWorkspacesForDeletion = `-- name: ListUserWorkspacesForDeletion :many
SELECT w.id, w.name, m.role,
    (SELECT count(*) FROM workspace_members o WHERE o.workspace_id = w.id)::int AS members,
    (SELECT count(*) FROM workspace_members o WHERE o.workspace_id = w.id AND o.role = 'owner')::int AS owners
FROM workspace_members m
JOIN workspaces w ON w.id = m.workspace_id
WHERE m.user_id = $1
ORDER BY lower(w.name), w.created_at
`

type ListUserWorkspacesForDeletionRow struct {
	ID      uuid.UUID
	Name    string
	Role    string
	Members int32
	Owners  int32
}

// The user's workspaces with what deleting the account means for each:
// how many members and owners it has.
func (q *Queries) ListUserWorkspacesForDeletion(ctx context.Context, userID uuid.UUID) ([]ListUserWorkspacesForDeletionRow, error) {
	rows, err := q.db.Query(ctx, listUserWorkspacesForDeletion, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserWorkspacesForDeletionRow{}
	for rows.Next() {
		var i ListUserWorkspacesForDeletionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Members,
			&i.Owners,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserWorkspaces = `-- name: LockUserWorkspaces :exec
SELECT 1
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE w.id IN (SELECT um.workspace_id FROM workspace_members um WHERE um.user_id = $1)
ORDER BY w.id, m.user_id
FOR UPDATE
`

// Locks the user's workspaces and their memberships, in a fixed order, so
// nobody joins, leaves or changes role while the account is deleted
// (adding a member needs a key share lock on the workspace row).
func (q *Queries) LockUserWorkspaces(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockUserWorkspaces, userID)
	return err
}

const scheduleUserDeletion = `-- name: ScheduleUserDeletion :one
UPDATE users SET deletion_scheduled_for = $2
WHERE id = $1 AND deletion_scheduled_for IS NULL
RETURNING id, email, name, locale, created_at, updated_at, deletion_scheduled_for
`

type ScheduleUserDeletionParams struct {
	ID                   uuid.UUID
	DeletionScheduledFor *time.Time
}

func (q *Queries) ScheduleUserDeletion(ctx context.Context, arg ScheduleUserDeletionParams) (User, error) {
	row := q.db.QueryRow(ctx, scheduleUserDeletion, arg.ID, arg.DeletionScheduledFor)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionScheduledFor,
	)
	return i, err
}
