// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activity_log (actor_id, channel, client_id, client_name, action, entity_type, entity_id, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertActivityParams struct {
	ActorID    *uuid.UUID
	Channel    string
	ClientID   *string
	ClientName *string
	Action     string
	EntityType string
	EntityID   uuid.UUID
	Details    []byte
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.Exec(ctx, insertActivity,
		arg.ActorID,
		arg.Channel,
		arg.ClientID,
		arg.ClientName,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
	)
	return err
}

const listActivity = `-- name: ListActivity :many
SELECT
    l.id, l.actor_id, l.channel, l.client_id, l.client_name, l.action,
    l.entity_type, l.entity_id, l.details, l.created_at,
    u.name AS actor_name,
    u.email AS actor_email
FROM activity_log l
LEFT JOIN users u ON u.id = l.actor_id
WHERE ($1::uuid IS NULL OR l.actor_id = $1)
  AND ($2::text IS NULL OR l.channel = $2)
  AND ($3::text IS NULL OR l.entity_type = $3)
  AND ($4::uuid IS NULL OR l.entity_id = $4)
  AND ($5::timestamptz IS NULL
       OR (l.created_at, l.id) < ($5, $6::uuid))
ORDER BY l.created_at DESC, l.id DESC
LIMIT $7
`

type ListActivityParams struct {
	ActorID         *uuid.UUID
	Channel         *string
	EntityType      *string
	EntityID        *uuid.UUID
	BeforeCreatedAt *time.Time
	BeforeID        *uuid.UUID
	RowLimit        int32
}

type ListActivityRow struct {
	ID         uuid.UUID
	ActorID    *uuid.UUID
	Channel    string
	ClientID   *string
	ClientName *string
	Action     string
	EntityType string
	EntityID   uuid.UUID
	Details    []byte
	CreatedAt  time.Time
	ActorName  *string
	ActorEmail *string
}

// ListActivity returns the workspace's entries newest first. The cursor is
// the (created_at, id) of the last entry of the previous page; callers ask
// for one row more than the page size to know whether another page exists.
func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity,
		arg.ActorID,
		arg.Channel,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRow{}
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Channel,
			&i.ClientID,
			&i.ClientName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
