// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeChallenge = `-- name: ConsumeChallenge :execrows
UPDATE login_challenges SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
`

// Consumes the challenge only if it is still open, so concurrent redemptions
// cannot both succeed.
func (q *Queries) ConsumeChallenge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOpenChallenges = `-- name: ConsumeOpenChallenges :exec
UPDATE login_challenges SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

// Invalidates every other open challenge once the user has logged in.
func (q *Queries) ConsumeOpenChallenges(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOpenChallenges, userID)
	return err
}

const countRecentChallenges = `-- name: CountRecentChallenges :one
SELECT count(*) FROM login_challenges
WHERE user_id = $1 AND created_at > $2
`

type CountRecentChallengesParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CountRecentChallenges(ctx context.Context, arg CountRecentChallengesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentChallenges, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO login_challenges (user_id, token_hash, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateChallengeParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	CodeHash  []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.UserID,
		arg.TokenHash,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, client, expires_at, workspace_id, user_agent, last_used_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, token_hash, client, expires_at, last_used_at, created_at, oauth_client_id, oauth_family_id, workspace_id, user_agent, scope
`

type CreateSessionParams struct {
	UserID      uuid.UUID
	TokenHash   []byte
	Client      string
	ExpiresAt   time.Time
	WorkspaceID *uuid.UUID
	UserAgent   string
	LastUsedAt  time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.Client,
		arg.ExpiresAt,
		arg.WorkspaceID,
		arg.UserAgent,
		arg.LastUsedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Client,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.OauthClientID,
		&i.OauthFamilyID,
		&i.WorkspaceID,
		&i.UserAgent,
		&i.Scope,
	)
	return i, err
}

const deleteExpiredAuthRecords = `-- name: DeleteExpiredAuthRecords :exec
WITH expired_sessions AS (
    DELETE FROM sessions
    WHERE sessions.expires_at < $1 OR sessions.last_used_at < $2
)
DELETE FROM login_challenges WHERE login_challenges.expires_at < $1
`

type DeleteExpiredAuthRecordsParams struct {
	Now       time.Time
	IdleSince time.Time
}

// Sessions end at their absolute expiry or after being idle too long.
func (q *Queries) DeleteExpiredAuthRecords(ctx context.Context, arg DeleteExpiredAuthRecordsParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthRecords, arg.Now, arg.IdleSince)
	return err
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :execrows
DELETE FROM sessions
WHERE user_id = $1 AND id <> $2 AND oauth_family_id IS NULL
`

type DeleteOtherUserSessionsParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :execrows
DELETE FROM users WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserByEmail, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSession = `-- name: DeleteUserSession :execrows
DELETE FROM sessions
WHERE id = $1 AND user_id = $2 AND oauth_family_id IS NULL
`

type DeleteUserSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Only the user's own sign-ins can be revoked this way; connected apps are
// disconnected through their OAuth grant.
func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChallengeByTokenHash = `-- name: GetChallengeByTokenHash :one
SELECT id, user_id, token_hash, code_hash, attempts, expires_at, consumed_at, created_at FROM login_challenges WHERE token_hash = $1
`

func (q *Queries) GetChallengeByTokenHash(ctx context.Context, tokenHash []byte) (LoginChallenge, error) {
	row := q.db.QueryRow(ctx, getChallengeByTokenHash, tokenHash)
	var i LoginChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultWorkspaceID = `-- name: GetDefaultWorkspaceID :one
SELECT m.workspace_id
FROM workspace_members m
WHERE m.user_id = $1
ORDER BY (
    SELECT max(s.last_used_at) FROM sessions s
    WHERE s.user_id = m.user_id AND s.workspace_id = m.workspace_id
) DESC NULLS LAST, m.created_at
LIMIT 1
`

// The workspace a new session starts in: the one the user used last, or
// the first one they joined.
func (q *Queries) GetDefaultWorkspaceID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDefaultWorkspaceID, userID)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getLatestOpenChallenge = `-- name: GetLatestOpenChallenge :one
SELECT id, user_id, token_hash, code_hash, attempts, expires_at, consumed_at, created_at FROM login_challenges
WHERE user_id = $1 AND consumed_at IS NULL AND expires_at > $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOpenChallengeParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) GetLatestOpenChallenge(ctx context.Context, arg GetLatestOpenChallengeParams) (LoginChallenge, error) {
	row := q.db.QueryRow(ctx, getLatestOpenChallenge, arg.UserID, arg.ExpiresAt)
	var i LoginChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT w.id, w.name, m.role
FROM workspace_members m
JOIN workspaces w ON w.id = m.workspace_id
WHERE m.workspace_id = $1 AND m.user_id = $2
`

type GetMembershipParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

type GetMembershipRow struct {
	ID   uuid.UUID
	Name string
	Role string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.WorkspaceID, arg.UserID)
	var i GetMembershipRow
	err := row.Scan(&i.ID, &i.Name, &i.Role)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.client, s.expires_at, s.last_used_at, s.created_at, s.oauth_client_id, s.oauth_family_id, s.workspace_id, s.user_agent, s.scope, u.email, u.name, u.locale,
    w.id AS active_workspace_id, w.name AS workspace_name, m.role AS workspace_role,
    oc.name AS oauth_client_name
FROM sessions s
JOIN users u ON u.id = s.user_id
LEFT JOIN oauth_clients oc ON oc.id = s.oauth_client_id
LEFT JOIN workspace_members m ON m.workspace_id = s.workspace_id AND m.user_id = s.user_id
LEFT JOIN workspaces w ON w.id = m.workspace_id
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	TokenHash         []byte
	Client            string
	ExpiresAt         time.Time
	LastUsedAt        time.Time
	CreatedAt         time.Time
	OauthClientID     *string
	OauthFamilyID     *uuid.UUID
	WorkspaceID       *uuid.UUID
	UserAgent         string
	Scope             string
	Email             string
	Name              string
	Locale            string
	ActiveWorkspaceID *uuid.UUID
	WorkspaceName     *string
	WorkspaceRole     *string
	OauthClientName   *string
}

// The session's workspace is only reported while the user is still a
// member of it.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Client,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.OauthClientID,
		&i.OauthFamilyID,
		&i.WorkspaceID,
		&i.UserAgent,
		&i.Scope,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.ActiveWorkspaceID,
		&i.WorkspaceName,
		&i.WorkspaceRole,
		&i.OauthClientName,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, locale, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, locale, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementChallengeAttempts = `-- name: IncrementChallengeAttempts :one
UPDATE login_challenges SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

func (q *Queries) IncrementChallengeAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementChallengeAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_agent, created_at, last_used_at, expires_at
FROM sessions
WHERE user_id = $1
  AND oauth_family_id IS NULL
  AND expires_at > $2
  AND last_used_at > $3
ORDER BY last_used_at DESC, created_at DESC
`

type ListUserSessionsParams struct {
	UserID    uuid.UUID
	Now       time.Time
	IdleSince time.Time
}

type ListUserSessionsRow struct {
	ID         uuid.UUID
	UserAgent  string
	CreatedAt  time.Time
	LastUsedAt time.Time
	ExpiresAt  time.Time
}

// The user's active sign-ins (not the access tokens of connected apps),
// most recently used first.
func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.UserID, arg.Now, arg.IdleSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, locale, created_at, updated_at FROM users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionWorkspace = `-- name: SetSessionWorkspace :exec
UPDATE sessions SET workspace_id = $2, last_used_at = now() WHERE id = $1
`

type SetSessionWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID *uuid.UUID
}

// Switching counts as using the session, so the next sign-in resumes the
// workspace the user switched to.
func (q *Queries) SetSessionWorkspace(ctx context.Context, arg SetSessionWorkspaceParams) error {
	_, err := q.db.Exec(ctx, setSessionWorkspace, arg.ID, arg.WorkspaceID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID         uuid.UUID
	LastUsedAt time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastUsedAt)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    name = COALESCE($1, name),
    locale = COALESCE($2, locale)
WHERE id = $3
RETURNING id, email, name, locale, created_at, updated_at
`

type UpdateUserParams struct {
	Name   *string
	Locale *string
	ID     uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.Locale, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email, name)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE SET name = CASE WHEN EXCLUDED.name = '' THEN users.name ELSE EXCLUDED.name END
RETURNING id, email, name, locale, created_at, updated_at
`

type UpsertUserParams struct {
	Email string
	Name  string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
