// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listBudgetRecurringExpenses = `-- name: ListBudgetRecurringExpenses :many
SELECT
    r.id,
    r.category_id,
    r.amount,
    r.interval_unit,
    r.interval_count,
    r.start_on,
    r.total_payments,
    a.currency,
    c.name AS category_name,
    c.color AS category_color,
    cur.minor_units
FROM recurring_items r
JOIN accounts a ON a.id = r.account_id
JOIN currencies cur ON cur.code = a.currency
LEFT JOIN categories c ON c.id = r.category_id
WHERE r.type = 'expense'
  AND r.status = 'active'
  AND ($1::uuid IS NULL OR a.owner_user_id = $1)
  AND (NOT $2::boolean OR a.owner_user_id IS NULL)
`

type ListBudgetRecurringExpensesParams struct {
	OwnerID    *uuid.UUID
	SharedOnly bool
}

type ListBudgetRecurringExpensesRow struct {
	ID            uuid.UUID
	CategoryID    *uuid.UUID
	Amount        int64
	IntervalUnit  string
	IntervalCount int32
	StartOn       time.Time
	TotalPayments *int32
	Currency      string
	CategoryName  *string
	CategoryColor *string
	MinorUnits    int16
}

// Active recurring expenses with the currency and owner of their account.
func (q *Queries) ListBudgetRecurringExpenses(ctx context.Context, arg ListBudgetRecurringExpensesParams) ([]ListBudgetRecurringExpensesRow, error) {
	rows, err := q.db.Query(ctx, listBudgetRecurringExpenses, arg.OwnerID, arg.SharedOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetRecurringExpensesRow{}
	for rows.Next() {
		var i ListBudgetRecurringExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Amount,
			&i.IntervalUnit,
			&i.IntervalCount,
			&i.StartOn,
			&i.TotalPayments,
			&i.Currency,
			&i.CategoryName,
			&i.CategoryColor,
			&i.MinorUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveBudgets = `-- name: ListEffectiveBudgets :many
SELECT DISTINCT ON (b.category_id, b.currency)
    b.category_id,
    b.currency,
    b.month AS source_month,
    b.amount_minor,
    c.name AS category_name,
    c.color AS category_color,
    c.archived_at AS category_archived_at,
    cur.minor_units
FROM budgets b
JOIN categories c ON c.id = b.category_id
JOIN currencies cur ON cur.code = b.currency
WHERE b.month <= $1::date
ORDER BY b.category_id, b.currency, b.month DESC
`

type ListEffectiveBudgetsRow struct {
	CategoryID         uuid.UUID
	Currency           string
	SourceMonth        time.Time
	AmountMinor        *int64
	CategoryName       string
	CategoryColor      *string
	CategoryArchivedAt *time.Time
	MinorUnits         int16
}

// The budget in force for the month per category and currency: the latest
// row on or before it. A null amount means the budget was cleared.
func (q *Queries) ListEffectiveBudgets(ctx context.Context, month time.Time) ([]ListEffectiveBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveBudgets, month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectiveBudgetsRow{}
	for rows.Next() {
		var i ListEffectiveBudgetsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Currency,
			&i.SourceMonth,
			&i.AmountMinor,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryArchivedAt,
			&i.MinorUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFirstExpenseByCategory = `-- name: ListFirstExpenseByCategory :many
SELECT t.category_id, a.currency, min(t.occurred_on)::date AS first_on
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.type = 'expense'
  AND t.category_id IS NOT NULL
  AND t.occurred_on <= $1
GROUP BY t.category_id, a.currency
`

type ListFirstExpenseByCategoryRow struct {
	CategoryID *uuid.UUID
	Currency   string
	FirstOn    time.Time
}

// Date of the first expense of each category in each currency, up to a date.
func (q *Queries) ListFirstExpenseByCategory(ctx context.Context, toDate time.Time) ([]ListFirstExpenseByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listFirstExpenseByCategory, toDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFirstExpenseByCategoryRow{}
	for rows.Next() {
		var i ListFirstExpenseByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.Currency, &i.FirstOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyExpenseByCategory = `-- name: ListMonthlyExpenseByCategory :many
SELECT
    t.category_id,
    a.currency,
    date_trunc('month', t.occurred_on)::date AS month,
    sum(t.amount)::bigint AS total
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.type = 'expense'
  AND t.category_id IS NOT NULL
  AND t.occurred_on BETWEEN $1 AND $2
GROUP BY t.category_id, a.currency, date_trunc('month', t.occurred_on)
ORDER BY t.category_id, a.currency, month
`

type ListMonthlyExpenseByCategoryParams struct {
	FromDate time.Time
	ToDate   time.Time
}

type ListMonthlyExpenseByCategoryRow struct {
	CategoryID *uuid.UUID
	Currency   string
	Month      time.Time
	Total      int64
}

// Expenses per category, currency and month in a date range. Transfers and
// income are not expenses; uncategorized expenses are left out.
func (q *Queries) ListMonthlyExpenseByCategory(ctx context.Context, arg ListMonthlyExpenseByCategoryParams) ([]ListMonthlyExpenseByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listMonthlyExpenseByCategory, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonthlyExpenseByCategoryRow{}
	for rows.Next() {
		var i ListMonthlyExpenseByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Currency,
			&i.Month,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringIDsPaidBetween = `-- name: ListRecurringIDsPaidBetween :many
SELECT DISTINCT recurring_id::uuid AS recurring_id
FROM transactions
WHERE recurring_id IS NOT NULL
  AND occurred_on BETWEEN $1 AND $2
`

type ListRecurringIDsPaidBetweenParams struct {
	FromDate time.Time
	ToDate   time.Time
}

// Recurring items with at least one linked transaction in a date range.
func (q *Queries) ListRecurringIDsPaidBetween(ctx context.Context, arg ListRecurringIDsPaidBetweenParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRecurringIDsPaidBetween, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var recurring_id uuid.UUID
		if err := rows.Scan(&recurring_id); err != nil {
			return nil, err
		}
		items = append(items, recurring_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO budgets (category_id, currency, month, amount_minor, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, category_id, currency, month)
DO UPDATE SET amount_minor = EXCLUDED.amount_minor
`

type UpsertBudgetParams struct {
	CategoryID  uuid.UUID
	Currency    string
	Month       time.Time
	AmountMinor *int64
	CreatedBy   *uuid.UUID
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.Exec(ctx, upsertBudget,
		arg.CategoryID,
		arg.Currency,
		arg.Month,
		arg.AmountMinor,
		arg.CreatedBy,
	)
	return err
}
