// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, kind, color, icon)
VALUES ($1, $2, $3, $4)
RETURNING id, name, kind, color, icon, archived_at, created_at, updated_at
`

type CreateCategoryParams struct {
	Name  string
	Kind  string
	Color *string
	Icon  *string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Kind,
		arg.Color,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.Icon,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, kind, color, icon, archived_at, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.Icon,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, kind, color, icon, archived_at, created_at, updated_at FROM categories
WHERE ($1::text IS NULL OR kind = $1)
  AND ($2::boolean OR archived_at IS NULL)
ORDER BY kind, archived_at IS NOT NULL, lower(name)
`

type ListCategoriesParams struct {
	Kind            *string
	IncludeArchived bool
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Kind, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Color,
			&i.Icon,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET
    name = COALESCE($1, name),
    color = CASE WHEN $2::boolean THEN $3 ELSE color END,
    icon = CASE WHEN $4::boolean THEN $5 ELSE icon END,
    archived_at = CASE
        WHEN $6::boolean IS NULL THEN archived_at
        WHEN $6::boolean THEN COALESCE(archived_at, now())
        ELSE NULL
    END
WHERE id = $7
RETURNING id, name, kind, color, icon, archived_at, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name     *string
	SetColor bool
	Color    *string
	SetIcon  bool
	Icon     *string
	Archived *bool
	ID       uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.SetColor,
		arg.Color,
		arg.SetIcon,
		arg.Icon,
		arg.Archived,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.Icon,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
