// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: currencies.sql

package store

import (
	"context"
)

const getCurrency = `-- name: GetCurrency :one
SELECT code, name, symbol, minor_units FROM currencies WHERE code = $1
`

func (q *Queries) GetCurrency(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.MinorUnits,
	)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT code, name, symbol, minor_units FROM currencies ORDER BY code
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.MinorUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
