// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Type        string
	Currency    string
	// Balance on balance_as_of, in minor units.
	InitialBalance int64
	ArchivedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	BalanceAsOf    time.Time
	OwnerUserID    *uuid.UUID
}

type Budget struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	CategoryID  uuid.UUID
	Currency    string
	Month       time.Time
	AmountMinor *int64
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Category struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Kind        string
	Color       *string
	Icon        *string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Currency struct {
	Code       string
	Name       string
	Symbol     string
	MinorUnits int16
}

type LoginChallenge struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CodeHash   []byte
	Attempts   int32
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type OauthAuthorizationCode struct {
	CodeHash      []byte
	ClientID      string
	UserID        uuid.UUID
	RedirectUri   string
	CodeChallenge string
	Scope         string
	WorkspaceID   *uuid.UUID
	ExpiresAt     time.Time
	UsedAt        *time.Time
	CreatedAt     time.Time
}

type OauthAuthorizationRequest struct {
	ID            uuid.UUID
	ClientID      string
	RedirectUri   string
	CodeChallenge string
	State         string
	Scope         string
	Resource      string
	Email         *string
	UserID        *uuid.UUID
	ExpiresAt     time.Time
	CreatedAt     time.Time
}

type OauthClient struct {
	ID                      string
	SecretHash              []byte
	Name                    string
	RedirectUris            []string
	TokenEndpointAuthMethod string
	CreatedAt               time.Time
}

type OauthGrant struct {
	ID          uuid.UUID
	ClientID    string
	UserID      uuid.UUID
	WorkspaceID *uuid.UUID
	Scope       string
	CreatedAt   time.Time
	LastUsedAt  time.Time
	RevokedAt   *time.Time
}

type OauthRefreshToken struct {
	TokenHash   []byte
	FamilyID    uuid.UUID
	ClientID    string
	UserID      uuid.UUID
	Scope       string
	WorkspaceID *uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type RecurringDismissedSuggestion struct {
	WorkspaceID uuid.UUID
	AccountID   uuid.UUID
	Type        string
	Description string
	DismissedBy *uuid.UUID
	DismissedAt time.Time
}

type RecurringItem struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	Name          string
	Type          string
	AccountID     uuid.UUID
	CategoryID    *uuid.UUID
	Amount        int64
	Notes         string
	IntervalUnit  string
	IntervalCount int32
	StartOn       time.Time
	TotalPayments *int32
	Status        string
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Session struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	TokenHash     []byte
	Client        string
	ExpiresAt     time.Time
	LastUsedAt    time.Time
	CreatedAt     time.Time
	OauthClientID *string
	OauthFamilyID *uuid.UUID
	WorkspaceID   *uuid.UUID
	UserAgent     string
}

type Transaction struct {
	ID                   uuid.UUID
	WorkspaceID          uuid.UUID
	Type                 string
	AccountID            uuid.UUID
	Amount               int64
	DestinationAccountID *uuid.UUID
	DestinationAmount    *int64
	CategoryID           *uuid.UUID
	Description          string
	OccurredOn           time.Time
	CreatedBy            *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	RecurringID          *uuid.UUID
	RecurringDueOn       *time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Locale    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Workspace struct {
	ID                   uuid.UUID
	Name                 string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletionScheduledFor *time.Time
	DeletionRequestedBy  *uuid.UUID
}

type WorkspaceInvitation struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	TokenHash   []byte
	InvitedBy   *uuid.UUID
	ExpiresAt   time.Time
	AcceptedAt  *time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	CreatedAt   time.Time
}
