// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID             uuid.UUID
	Name           string
	Type           string
	Currency       string
	InitialBalance int64
	ArchivedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Category struct {
	ID         uuid.UUID
	Name       string
	Kind       string
	Color      *string
	Icon       *string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Currency struct {
	Code       string
	Name       string
	Symbol     string
	MinorUnits int16
}

type LoginChallenge struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CodeHash   []byte
	Attempts   int32
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type OauthAuthorizationCode struct {
	CodeHash      []byte
	ClientID      string
	UserID        uuid.UUID
	RedirectUri   string
	CodeChallenge string
	Scope         string
	ExpiresAt     time.Time
	UsedAt        *time.Time
	CreatedAt     time.Time
}

type OauthAuthorizationRequest struct {
	ID            uuid.UUID
	ClientID      string
	RedirectUri   string
	CodeChallenge string
	State         string
	Scope         string
	Resource      string
	Email         *string
	ExpiresAt     time.Time
	CreatedAt     time.Time
}

type OauthClient struct {
	ID                      string
	SecretHash              []byte
	Name                    string
	RedirectUris            []string
	TokenEndpointAuthMethod string
	CreatedAt               time.Time
}

type OauthRefreshToken struct {
	TokenHash []byte
	FamilyID  uuid.UUID
	ClientID  string
	UserID    uuid.UUID
	Scope     string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type Session struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	TokenHash     []byte
	Client        string
	ExpiresAt     time.Time
	LastUsedAt    time.Time
	CreatedAt     time.Time
	OauthClientID *string
	OauthFamilyID *uuid.UUID
}

type Transaction struct {
	ID                   uuid.UUID
	Type                 string
	AccountID            uuid.UUID
	Amount               int64
	DestinationAccountID *uuid.UUID
	DestinationAmount    *int64
	CategoryID           *uuid.UUID
	Description          string
	OccurredOn           time.Time
	CreatedBy            *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Locale    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
