// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRecentOAuthClients = `-- name: CountRecentOAuthClients :one
SELECT count(*) FROM oauth_clients WHERE created_at > $1
`

func (q *Queries) CountRecentOAuthClients(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOAuthClients, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :exec
INSERT INTO oauth_authorization_codes (code_hash, client_id, user_id, redirect_uri, code_challenge, scope, workspace_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuthorizationCodeParams struct {
	CodeHash      []byte
	ClientID      string
	UserID        uuid.UUID
	RedirectUri   string
	CodeChallenge string
	Scope         string
	WorkspaceID   *uuid.UUID
	ExpiresAt     time.Time
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) error {
	_, err := q.db.Exec(ctx, createAuthorizationCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.Scope,
		arg.WorkspaceID,
		arg.ExpiresAt,
	)
	return err
}

const createAuthorizationRequest = `-- name: CreateAuthorizationRequest :one
INSERT INTO oauth_authorization_requests (client_id, redirect_uri, code_challenge, state, scope, resource, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, client_id, redirect_uri, code_challenge, state, scope, resource, email, user_id, expires_at, created_at
`

type CreateAuthorizationRequestParams struct {
	ClientID      string
	RedirectUri   string
	CodeChallenge string
	State         string
	Scope         string
	Resource      string
	ExpiresAt     time.Time
}

func (q *Queries) CreateAuthorizationRequest(ctx context.Context, arg CreateAuthorizationRequestParams) (OauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, createAuthorizationRequest,
		arg.ClientID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.State,
		arg.Scope,
		arg.Resource,
		arg.ExpiresAt,
	)
	var i OauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.State,
		&i.Scope,
		&i.Resource,
		&i.Email,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (id, secret_hash, name, redirect_uris, token_endpoint_auth_method)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, secret_hash, name, redirect_uris, token_endpoint_auth_method, created_at
`

type CreateOAuthClientParams struct {
	ID                      string
	SecretHash              []byte
	Name                    string
	RedirectUris            []string
	TokenEndpointAuthMethod string
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.ID,
		arg.SecretHash,
		arg.Name,
		arg.RedirectUris,
		arg.TokenEndpointAuthMethod,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthGrant = `-- name: CreateOAuthGrant :exec
INSERT INTO oauth_grants (id, client_id, user_id, workspace_id, scope)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOAuthGrantParams struct {
	ID          uuid.UUID
	ClientID    string
	UserID      uuid.UUID
	WorkspaceID *uuid.UUID
	Scope       string
}

func (q *Queries) CreateOAuthGrant(ctx context.Context, arg CreateOAuthGrantParams) error {
	_, err := q.db.Exec(ctx, createOAuthGrant,
		arg.ID,
		arg.ClientID,
		arg.UserID,
		arg.WorkspaceID,
		arg.Scope,
	)
	return err
}

const createOAuthSession = `-- name: CreateOAuthSession :one
INSERT INTO sessions (user_id, token_hash, client, expires_at, oauth_client_id, oauth_family_id, workspace_id, scope)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateOAuthSessionParams struct {
	UserID        uuid.UUID
	TokenHash     []byte
	Client        string
	ExpiresAt     time.Time
	OauthClientID *string
	OauthFamilyID *uuid.UUID
	WorkspaceID   *uuid.UUID
	Scope         string
}

func (q *Queries) CreateOAuthSession(ctx context.Context, arg CreateOAuthSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOAuthSession,
		arg.UserID,
		arg.TokenHash,
		arg.Client,
		arg.ExpiresAt,
		arg.OauthClientID,
		arg.OauthFamilyID,
		arg.WorkspaceID,
		arg.Scope,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO oauth_refresh_tokens (token_hash, family_id, client_id, user_id, scope, workspace_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRefreshTokenParams struct {
	TokenHash   []byte
	FamilyID    uuid.UUID
	ClientID    string
	UserID      uuid.UUID
	Scope       string
	WorkspaceID *uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.TokenHash,
		arg.FamilyID,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.WorkspaceID,
		arg.ExpiresAt,
	)
	return err
}

const deleteAuthorizationRequest = `-- name: DeleteAuthorizationRequest :exec
DELETE FROM oauth_authorization_requests WHERE id = $1
`

func (q *Queries) DeleteAuthorizationRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthorizationRequest, id)
	return err
}

const deleteExpiredOAuthRecords = `-- name: DeleteExpiredOAuthRecords :exec
WITH expired_requests AS (
    DELETE FROM oauth_authorization_requests WHERE oauth_authorization_requests.expires_at < $1
), expired_codes AS (
    DELETE FROM oauth_authorization_codes WHERE oauth_authorization_codes.expires_at < $1
)
DELETE FROM oauth_refresh_tokens WHERE oauth_refresh_tokens.expires_at < $1
`

func (q *Queries) DeleteExpiredOAuthRecords(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthRecords, expiresAt)
	return err
}

const deleteFamilySessions = `-- name: DeleteFamilySessions :exec
DELETE FROM sessions WHERE oauth_family_id = $1
`

func (q *Queries) DeleteFamilySessions(ctx context.Context, oauthFamilyID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFamilySessions, oauthFamilyID)
	return err
}

const deleteOrphanOAuthGrants = `-- name: DeleteOrphanOAuthGrants :exec
DELETE FROM oauth_grants g
WHERE NOT EXISTS (SELECT 1 FROM oauth_refresh_tokens t WHERE t.family_id = g.id)
`

// Grants whose refresh tokens have all been purged can no longer be used.
// A grant is created in the same transaction as its first refresh token.
func (q *Queries) DeleteOrphanOAuthGrants(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOrphanOAuthGrants)
	return err
}

const getAuthorizationCode = `-- name: GetAuthorizationCode :one
SELECT code_hash, client_id, user_id, redirect_uri, code_challenge, scope, workspace_id, expires_at, used_at, created_at FROM oauth_authorization_codes WHERE code_hash = $1
`

func (q *Queries) GetAuthorizationCode(ctx context.Context, codeHash []byte) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCode, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.Scope,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorizationRequest = `-- name: GetAuthorizationRequest :one
SELECT r.id, r.client_id, r.redirect_uri, r.code_challenge, r.state, r.scope, r.resource, r.email, r.user_id, r.expires_at, r.created_at, c.name AS client_name
FROM oauth_authorization_requests r
JOIN oauth_clients c ON c.id = r.client_id
WHERE r.id = $1
`

type GetAuthorizationRequestRow struct {
	ID            uuid.UUID
	ClientID      string
	RedirectUri   string
	CodeChallenge string
	State         string
	Scope         string
	Resource      string
	Email         *string
	UserID        *uuid.UUID
	ExpiresAt     time.Time
	CreatedAt     time.Time
	ClientName    string
}

func (q *Queries) GetAuthorizationRequest(ctx context.Context, id uuid.UUID) (GetAuthorizationRequestRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizationRequest, id)
	var i GetAuthorizationRequestRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.State,
		&i.Scope,
		&i.Resource,
		&i.Email,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ClientName,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, secret_hash, name, redirect_uris, token_endpoint_auth_method, created_at FROM oauth_clients WHERE id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token_hash, family_id, client_id, user_id, scope, workspace_id, expires_at, revoked_at, created_at FROM oauth_refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i OauthRefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.FamilyID,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionFamily = `-- name: GetSessionFamily :one
SELECT oauth_family_id FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionFamily(ctx context.Context, tokenHash []byte) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionFamily, tokenHash)
	var oauth_family_id *uuid.UUID
	err := row.Scan(&oauth_family_id)
	return oauth_family_id, err
}

const listUserOAuthGrants = `-- name: ListUserOAuthGrants :many
SELECT g.id, c.name AS client_name, g.workspace_id, w.name AS workspace_name, g.scope, g.created_at,
    greatest(g.last_used_at, (
        SELECT max(s.last_used_at) FROM sessions s WHERE s.oauth_family_id = g.id
    ))::timestamptz AS last_used_at
FROM oauth_grants g
JOIN oauth_clients c ON c.id = g.client_id
LEFT JOIN workspaces w ON w.id = g.workspace_id
WHERE g.user_id = $1
  AND g.revoked_at IS NULL
  AND EXISTS (
    SELECT 1 FROM oauth_refresh_tokens t
    WHERE t.family_id = g.id AND t.revoked_at IS NULL AND t.expires_at > $2
  )
ORDER BY last_used_at DESC, g.created_at DESC
`

type ListUserOAuthGrantsParams struct {
	UserID uuid.UUID
	Now    time.Time
}

type ListUserOAuthGrantsRow struct {
	ID            uuid.UUID
	ClientName    string
	WorkspaceID   *uuid.UUID
	WorkspaceName *string
	Scope         string
	CreatedAt     time.Time
	LastUsedAt    time.Time
}

// The user's connected apps: grants with a refresh token still usable.
// Last use is the latest refresh or call made with one of its access tokens.
func (q *Queries) ListUserOAuthGrants(ctx context.Context, arg ListUserOAuthGrantsParams) ([]ListUserOAuthGrantsRow, error) {
	rows, err := q.db.Query(ctx, listUserOAuthGrants, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOAuthGrantsRow{}
	for rows.Next() {
		var i ListUserOAuthGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.WorkspaceID,
			&i.WorkspaceName,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOAuthGrant = `-- name: LockOAuthGrant :one
SELECT id, client_id, user_id, workspace_id, scope, created_at, last_used_at, revoked_at FROM oauth_grants WHERE id = $1 FOR UPDATE
`

// Locks the grant so its tokens are issued and revoked one flow at a time:
// every flow that issues or revokes a grant's tokens takes this lock first.
func (q *Queries) LockOAuthGrant(ctx context.Context, id uuid.UUID) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, lockOAuthGrant, id)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeOAuthGrant = `-- name: RevokeOAuthGrant :exec
UPDATE oauth_grants SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeOAuthGrant, id)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE oauth_refresh_tokens SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE oauth_refresh_tokens SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
RETURNING token_hash, family_id, client_id, user_id, scope, workspace_id, expires_at, revoked_at, created_at
`

// Revokes the token and returns it, only if it was still active.
func (q *Queries) RotateRefreshToken(ctx context.Context, tokenHash []byte) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, tokenHash)
	var i OauthRefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.FamilyID,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setAuthorizationRequestEmail = `-- name: SetAuthorizationRequestEmail :exec
UPDATE oauth_authorization_requests SET email = $2 WHERE id = $1
`

type SetAuthorizationRequestEmailParams struct {
	ID    uuid.UUID
	Email *string
}

func (q *Queries) SetAuthorizationRequestEmail(ctx context.Context, arg SetAuthorizationRequestEmailParams) error {
	_, err := q.db.Exec(ctx, setAuthorizationRequestEmail, arg.ID, arg.Email)
	return err
}

const setAuthorizationRequestUser = `-- name: SetAuthorizationRequestUser :exec
UPDATE oauth_authorization_requests SET user_id = $2, scope = $3 WHERE id = $1
`

type SetAuthorizationRequestUserParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
	Scope  string
}

// Records who signed in and the access they chose, while they pick the
// workspace.
func (q *Queries) SetAuthorizationRequestUser(ctx context.Context, arg SetAuthorizationRequestUserParams) error {
	_, err := q.db.Exec(ctx, setAuthorizationRequestUser, arg.ID, arg.UserID, arg.Scope)
	return err
}

const touchOAuthGrant = `-- name: TouchOAuthGrant :exec
UPDATE oauth_grants SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchOAuthGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchOAuthGrant, id)
	return err
}

const useAuthorizationCode = `-- name: UseAuthorizationCode :one
UPDATE oauth_authorization_codes SET used_at = now()
WHERE code_hash = $1 AND used_at IS NULL
RETURNING code_hash, client_id, user_id, redirect_uri, code_challenge, scope, workspace_id, expires_at, used_at, created_at
`

// Marks the code as used and returns it, only if it was unused.
func (q *Queries) UseAuthorizationCode(ctx context.Context, codeHash []byte) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, useAuthorizationCode, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.Scope,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
