// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRecurringItem = `-- name: CreateRecurringItem :one
INSERT INTO recurring_items (
    name, type, account_id, category_id, amount, notes,
    interval_unit, interval_count, start_on, total_payments, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateRecurringItemParams struct {
	Name          string
	Type          string
	AccountID     uuid.UUID
	CategoryID    *uuid.UUID
	Amount        int64
	Notes         string
	IntervalUnit  string
	IntervalCount int32
	StartOn       time.Time
	TotalPayments *int32
	CreatedBy     *uuid.UUID
}

func (q *Queries) CreateRecurringItem(ctx context.Context, arg CreateRecurringItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRecurringItem,
		arg.Name,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Notes,
		arg.IntervalUnit,
		arg.IntervalCount,
		arg.StartOn,
		arg.TotalPayments,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findOpenRecurringItemByName = `-- name: FindOpenRecurringItemByName :one
SELECT id, name, status FROM recurring_items
WHERE lower(name) = lower($1) AND status <> 'cancelled' AND id <> $2
LIMIT 1
`

type FindOpenRecurringItemByNameParams struct {
	Lower string
	ID    uuid.UUID
}

type FindOpenRecurringItemByNameRow struct {
	ID     uuid.UUID
	Name   string
	Status string
}

func (q *Queries) FindOpenRecurringItemByName(ctx context.Context, arg FindOpenRecurringItemByNameParams) (FindOpenRecurringItemByNameRow, error) {
	row := q.db.QueryRow(ctx, findOpenRecurringItemByName, arg.Lower, arg.ID)
	var i FindOpenRecurringItemByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const getRecurringItem = `-- name: GetRecurringItem :one
SELECT
    r.id, r.name, r.type, r.account_id, r.category_id, r.amount, r.notes, r.interval_unit, r.interval_count, r.start_on, r.total_payments, r.status, r.created_by, r.created_at, r.updated_at,
    a.name AS account_name,
    a.currency,
    a.archived_at AS account_archived_at,
    cur.minor_units,
    c.name AS category_name
FROM recurring_items r
JOIN accounts a ON a.id = r.account_id
JOIN currencies cur ON cur.code = a.currency
LEFT JOIN categories c ON c.id = r.category_id
WHERE r.id = $1
`

type GetRecurringItemRow struct {
	ID                uuid.UUID
	Name              string
	Type              string
	AccountID         uuid.UUID
	CategoryID        *uuid.UUID
	Amount            int64
	Notes             string
	IntervalUnit      string
	IntervalCount     int32
	StartOn           time.Time
	TotalPayments     *int32
	Status            string
	CreatedBy         *uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AccountName       string
	Currency          string
	AccountArchivedAt *time.Time
	MinorUnits        int16
	CategoryName      *string
}

func (q *Queries) GetRecurringItem(ctx context.Context, id uuid.UUID) (GetRecurringItemRow, error) {
	row := q.db.QueryRow(ctx, getRecurringItem, id)
	var i GetRecurringItemRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Notes,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.StartOn,
		&i.TotalPayments,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountName,
		&i.Currency,
		&i.AccountArchivedAt,
		&i.MinorUnits,
		&i.CategoryName,
	)
	return i, err
}

const listRecurringItems = `-- name: ListRecurringItems :many
SELECT
    r.id, r.name, r.type, r.account_id, r.category_id, r.amount, r.notes, r.interval_unit, r.interval_count, r.start_on, r.total_payments, r.status, r.created_by, r.created_at, r.updated_at,
    a.name AS account_name,
    a.currency,
    a.archived_at AS account_archived_at,
    cur.minor_units,
    c.name AS category_name
FROM recurring_items r
JOIN accounts a ON a.id = r.account_id
JOIN currencies cur ON cur.code = a.currency
LEFT JOIN categories c ON c.id = r.category_id
WHERE ($1::text IS NULL OR r.status = $1)
  AND ($2::text IS NULL OR r.type = $2)
ORDER BY r.status <> 'active', lower(r.name), r.created_at
`

type ListRecurringItemsParams struct {
	Status *string
	Type   *string
}

type ListRecurringItemsRow struct {
	ID                uuid.UUID
	Name              string
	Type              string
	AccountID         uuid.UUID
	CategoryID        *uuid.UUID
	Amount            int64
	Notes             string
	IntervalUnit      string
	IntervalCount     int32
	StartOn           time.Time
	TotalPayments     *int32
	Status            string
	CreatedBy         *uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AccountName       string
	Currency          string
	AccountArchivedAt *time.Time
	MinorUnits        int16
	CategoryName      *string
}

func (q *Queries) ListRecurringItems(ctx context.Context, arg ListRecurringItemsParams) ([]ListRecurringItemsRow, error) {
	rows, err := q.db.Query(ctx, listRecurringItems, arg.Status, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringItemsRow{}
	for rows.Next() {
		var i ListRecurringItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Notes,
			&i.IntervalUnit,
			&i.IntervalCount,
			&i.StartOn,
			&i.TotalPayments,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
			&i.Currency,
			&i.AccountArchivedAt,
			&i.MinorUnits,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringLastPayments = `-- name: ListRecurringLastPayments :many
SELECT DISTINCT ON (recurring_id)
    recurring_id, id, occurred_on, amount, recurring_due_on
FROM transactions
WHERE recurring_id = ANY($1::uuid[])
ORDER BY recurring_id, occurred_on DESC, created_at DESC, id
`

type ListRecurringLastPaymentsRow struct {
	RecurringID    *uuid.UUID
	ID             uuid.UUID
	OccurredOn     time.Time
	Amount         int64
	RecurringDueOn *time.Time
}

func (q *Queries) ListRecurringLastPayments(ctx context.Context, itemIds []uuid.UUID) ([]ListRecurringLastPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listRecurringLastPayments, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringLastPaymentsRow{}
	for rows.Next() {
		var i ListRecurringLastPaymentsRow
		if err := rows.Scan(
			&i.RecurringID,
			&i.ID,
			&i.OccurredOn,
			&i.Amount,
			&i.RecurringDueOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringPaidPeriods = `-- name: ListRecurringPaidPeriods :many
SELECT DISTINCT recurring_id, recurring_due_on
FROM transactions
WHERE recurring_id = ANY($1::uuid[])
`

type ListRecurringPaidPeriodsRow struct {
	RecurringID    *uuid.UUID
	RecurringDueOn *time.Time
}

func (q *Queries) ListRecurringPaidPeriods(ctx context.Context, itemIds []uuid.UUID) ([]ListRecurringPaidPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listRecurringPaidPeriods, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringPaidPeriodsRow{}
	for rows.Next() {
		var i ListRecurringPaidPeriodsRow
		if err := rows.Scan(&i.RecurringID, &i.RecurringDueOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringItem = `-- name: UpdateRecurringItem :exec
UPDATE recurring_items SET
    name = $2,
    category_id = $3,
    amount = $4,
    notes = $5,
    interval_unit = $6,
    interval_count = $7,
    start_on = $8,
    total_payments = $9,
    status = $10
WHERE id = $1
`

type UpdateRecurringItemParams struct {
	ID            uuid.UUID
	Name          string
	CategoryID    *uuid.UUID
	Amount        int64
	Notes         string
	IntervalUnit  string
	IntervalCount int32
	StartOn       time.Time
	TotalPayments *int32
	Status        string
}

func (q *Queries) UpdateRecurringItem(ctx context.Context, arg UpdateRecurringItemParams) error {
	_, err := q.db.Exec(ctx, updateRecurringItem,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.Amount,
		arg.Notes,
		arg.IntervalUnit,
		arg.IntervalCount,
		arg.StartOn,
		arg.TotalPayments,
		arg.Status,
	)
	return err
}
