// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summary.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const summaryByCategory = `-- name: SummaryByCategory :many

SELECT
    a.currency,
    t.type,
    t.category_id,
    c.name AS category_name,
    c.color AS category_color,
    sum(t.amount)::bigint AS total,
    count(*) AS transaction_count
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.type IN ('income', 'expense')
  AND t.occurred_on BETWEEN $1 AND $2
GROUP BY a.currency, t.type, t.category_id, c.name, c.color
ORDER BY a.currency, t.type, total DESC
`

type SummaryByCategoryParams struct {
	FromDate time.Time
	ToDate   time.Time
}

type SummaryByCategoryRow struct {
	Currency         string
	Type             string
	CategoryID       *uuid.UUID
	CategoryName     *string
	CategoryColor    *string
	Total            int64
	TransactionCount int64
}

// Income and expense totals per currency and category for a date range.
// Transfers are excluded: they move money between accounts but are neither
// income nor expense.
func (q *Queries) SummaryByCategory(ctx context.Context, arg SummaryByCategoryParams) ([]SummaryByCategoryRow, error) {
	rows, err := q.db.Query(ctx, summaryByCategory, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryByCategoryRow{}
	for rows.Next() {
		var i SummaryByCategoryRow
		if err := rows.Scan(
			&i.Currency,
			&i.Type,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.Total,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
