// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    type, account_id, amount, destination_account_id, destination_amount,
    category_id, description, occurred_on, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id
`

type CreateTransactionParams struct {
	Type                 string
	AccountID            uuid.UUID
	Amount               int64
	DestinationAccountID *uuid.UUID
	DestinationAmount    *int64
	CategoryID           *uuid.UUID
	Description          string
	OccurredOn           time.Time
	CreatedBy            *uuid.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Type,
		arg.AccountID,
		arg.Amount,
		arg.DestinationAccountID,
		arg.DestinationAmount,
		arg.CategoryID,
		arg.Description,
		arg.OccurredOn,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT
    t.id, t.type, t.account_id, t.amount, t.destination_account_id, t.destination_amount, t.category_id, t.description, t.occurred_on, t.created_by, t.created_at, t.updated_at,
    a.name AS account_name,
    a.currency AS currency,
    cur.minor_units AS minor_units,
    da.name AS destination_account_name,
    da.currency AS destination_currency,
    dcur.minor_units AS destination_minor_units,
    c.name AS category_name,
    u.name AS created_by_name,
    u.email AS created_by_email
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN currencies cur ON cur.code = a.currency
LEFT JOIN accounts da ON da.id = t.destination_account_id
LEFT JOIN currencies dcur ON dcur.code = da.currency
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN users u ON u.id = t.created_by
WHERE t.id = $1
`

type GetTransactionRow struct {
	ID                     uuid.UUID
	Type                   string
	AccountID              uuid.UUID
	Amount                 int64
	DestinationAccountID   *uuid.UUID
	DestinationAmount      *int64
	CategoryID             *uuid.UUID
	Description            string
	OccurredOn             time.Time
	CreatedBy              *uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	AccountName            string
	Currency               string
	MinorUnits             int16
	DestinationAccountName *string
	DestinationCurrency    *string
	DestinationMinorUnits  *int16
	CategoryName           *string
	CreatedByName          *string
	CreatedByEmail         *string
}

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.Amount,
		&i.DestinationAccountID,
		&i.DestinationAmount,
		&i.CategoryID,
		&i.Description,
		&i.OccurredOn,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountName,
		&i.Currency,
		&i.MinorUnits,
		&i.DestinationAccountName,
		&i.DestinationCurrency,
		&i.DestinationMinorUnits,
		&i.CategoryName,
		&i.CreatedByName,
		&i.CreatedByEmail,
	)
	return i, err
}

const getTransactionRecord = `-- name: GetTransactionRecord :one
SELECT id, type, account_id, amount, destination_account_id, destination_amount, category_id, description, occurred_on, created_by, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionRecord(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionRecord, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.Amount,
		&i.DestinationAccountID,
		&i.DestinationAmount,
		&i.CategoryID,
		&i.Description,
		&i.OccurredOn,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id, t.type, t.account_id, t.amount, t.destination_account_id, t.destination_amount, t.category_id, t.description, t.occurred_on, t.created_by, t.created_at, t.updated_at,
    a.name AS account_name,
    a.currency AS currency,
    cur.minor_units AS minor_units,
    da.name AS destination_account_name,
    da.currency AS destination_currency,
    dcur.minor_units AS destination_minor_units,
    c.name AS category_name,
    u.name AS created_by_name,
    u.email AS created_by_email,
    count(*) OVER () AS total_count
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN currencies cur ON cur.code = a.currency
LEFT JOIN accounts da ON da.id = t.destination_account_id
LEFT JOIN currencies dcur ON dcur.code = da.currency
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN users u ON u.id = t.created_by
WHERE ($1::uuid IS NULL
        OR t.account_id = $1
        OR t.destination_account_id = $1)
  AND ($2::uuid IS NULL OR t.category_id = $2)
  AND ($3::text IS NULL OR t.type = $3)
  AND ($4::date IS NULL OR t.occurred_on >= $4)
  AND ($5::date IS NULL OR t.occurred_on <= $5)
  AND ($6::text IS NULL OR t.description ILIKE '%' || $6 || '%')
ORDER BY t.occurred_on DESC, t.created_at DESC, t.id
LIMIT $8 OFFSET $7
`

type ListTransactionsParams struct {
	AccountID  *uuid.UUID
	CategoryID *uuid.UUID
	Type       *string
	FromDate   *time.Time
	ToDate     *time.Time
	Search     *string
	RowOffset  int32
	RowLimit   int32
}

type ListTransactionsRow struct {
	ID                     uuid.UUID
	Type                   string
	AccountID              uuid.UUID
	Amount                 int64
	DestinationAccountID   *uuid.UUID
	DestinationAmount      *int64
	CategoryID             *uuid.UUID
	Description            string
	OccurredOn             time.Time
	CreatedBy              *uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	AccountName            string
	Currency               string
	MinorUnits             int16
	DestinationAccountName *string
	DestinationCurrency    *string
	DestinationMinorUnits  *int16
	CategoryName           *string
	CreatedByName          *string
	CreatedByEmail         *string
	TotalCount             int64
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.FromDate,
		arg.ToDate,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AccountID,
			&i.Amount,
			&i.DestinationAccountID,
			&i.DestinationAmount,
			&i.CategoryID,
			&i.Description,
			&i.OccurredOn,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
			&i.Currency,
			&i.MinorUnits,
			&i.DestinationAccountName,
			&i.DestinationCurrency,
			&i.DestinationMinorUnits,
			&i.CategoryName,
			&i.CreatedByName,
			&i.CreatedByEmail,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions SET
    type = $2,
    account_id = $3,
    amount = $4,
    destination_account_id = $5,
    destination_amount = $6,
    category_id = $7,
    description = $8,
    occurred_on = $9
WHERE id = $1
`

type UpdateTransactionParams struct {
	ID                   uuid.UUID
	Type                 string
	AccountID            uuid.UUID
	Amount               int64
	DestinationAccountID *uuid.UUID
	DestinationAmount    *int64
	CategoryID           *uuid.UUID
	Description          string
	OccurredOn           time.Time
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.Exec(ctx, updateTransaction,
		arg.ID,
		arg.Type,
		arg.AccountID,
		arg.Amount,
		arg.DestinationAccountID,
		arg.DestinationAmount,
		arg.CategoryID,
		arg.Description,
		arg.OccurredOn,
	)
	return err
}
